apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: prod
    team: platform

spec:
  project: default

  source:
    repoURL: https://github.com/savitras/eks-gitops-pipeline
    targetRevision: main
    path: helm/order-service
    helm:
      releaseName: order-service
      valueFiles:
        - ../../gitops/environments/prod/values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: order-service-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
