# Production environment overrides
replicaCount: 3

image:
  repository: "463884819203.dkr.ecr.us-east-1.amazonaws.com/order-service"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

env:
  APP_VERSION: "production"
  NODE_ENV: "production"

rollout:
  enabled: true
