# Dev environment overrides
replicaCount: 1

image:
  repository: "463884819203.dkr.ecr.us-east-1.amazonaws.com/order-service"
  tag: "latest"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

env:
  APP_VERSION: "dev"
  NODE_ENV: "development"
