{{- if .Values.rollout.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "order-service.fullname" . }}-stable
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: order-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "order-service.fullname" . }}-stable
                port:
                  number: 80
{{- end }}
